CREATE TABLE IF NOT EXISTS STAFFS(staffid VARCHAR(60) NOT NULL PRIMARY KEY, encoded_password VARCHAR(256) NOT NULL, role INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS REPORTS(report_id INT PRIMARY KEY AUTO_INCREMENT, created_when TIMESTAMP NOT NULL, content VARCHAR(50000) NOT NULL);
CREATE TABLE IF NOT EXISTS COMMENTS(comment_id INT PRIMARY KEY AUTO_INCREMENT, report_id INT, staffid VARCHAR(60) NOT NULL, comment VARCHAR(50000) NOT NULL);
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_STAFFID FOREIGN KEY(staffid) REFERENCES STAFFS(staffid) ON DELETE CASCADE;
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_REPORTID FOREIGN KEY(report_id)  REFERENCES REPORTS(report_id) ON DELETE CASCADE;
